import type { Metadata } from "next";
import "./ui/globals.css";

import Navbar from "./ui/navbar/navbar";
import { jetbrains } from "./ui/fonts";


export const metadata: Metadata = {
  title: "ed.dev",
  icons: '/eddev.png',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrains.className} p-0 m-0 box-border text-black antialiased`}
      >
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
